// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCFEOH-AsmiJL3j_74zMPLbObUvkXO_JRg',
    appId: '1:836022818923:web:18076bc7496f2c2b88f92e',
    messagingSenderId: '836022818923',
    projectId: 'ngoding-lok',
    authDomain: 'ngoding-lok.firebaseapp.com',
    storageBucket: 'ngoding-lok.firebasestorage.app',
    measurementId: 'G-MBHSWQ1CD6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC57Tgu5b-Ft2Dfcnoa7mdNcgrHTUv02rY',
    appId: '1:836022818923:android:2cbabd82442888e688f92e',
    messagingSenderId: '836022818923',
    projectId: 'ngoding-lok',
    storageBucket: 'ngoding-lok.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCFEOH-AsmiJL3j_74zMPLbObUvkXO_JRg',
    appId: '1:836022818923:web:91877030085da79388f92e',
    messagingSenderId: '836022818923',
    projectId: 'ngoding-lok',
    authDomain: 'ngoding-lok.firebaseapp.com',
    storageBucket: 'ngoding-lok.firebasestorage.app',
    measurementId: 'G-TGRPG1EHMV',
  );
}
